AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*/rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  Rails:
    Enabled: fales
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 17